//
//  EPStrMacro.h
//  Ellipal_update
//
//  Created by cyl on 2018/8/15.
//  Copyright © 2018年 afuiot. All rights reserved.
//

#ifndef EPStrMacro_h
#define EPStrMacro_h

#define kEPWashNumber @"kEPWashNumber"
#define kEPWinStatus @"kEPWinStatus"
#define kEPBetch @"kEPBetch"
#define kEPCompensate @"kEPCompensate"
#define kEPshouldShazhu @"kEPshouldShazhu"
#define kEPReadChipMoney @"kEPReadChipMoney"
#define kEPRealCompensate @"kEPRealCompensate"
#define kEPAllChip @"kEPAllChip"
#define kEPChangeXueci @"kEPChangeXueci"
#define kEPBindChip @"kEPBindChip"
#define kEPCancellationChip @"kEPCancellationChip"
#define kEPEntry @"kEPEntry"
#define kEPNewGame @"kEPNewGame"
#define kEPWin @"kEPWin"
#define kEPLose @"kEPLose"
#define kEPZhuang @"kEPZhuang"
#define kEPXian @"kEPXian"
#define kEPZhuangDuizi @"kEPZhuangDuizi"
#define kEPXianDuizi @"kEPXianDuizi"
#define kEPHe @"kEPHe"
#define kEPBaoxian @"kEPBaoxian"
#define kEPSixWin @"kEPSixWin"
#define kEPZhuangSixWin @"kEPZhuangSixWin"
#define kEPTipsInfo @"kEPTipsInfo"
#define kEPReadSucceed @"kEPReadSucceed"
#define kEPNextTips @"kEPNextTips"
#define kEPConfirm @"kEPConfirm"
#define kEPCancel @"kEPCancel"
#define kEPShazhuSucceed @"kEPShazhuSucceed"
#define kEPZhuangDui @"kEPZhuangDui"
#define kEPXianDui @"kEPXianDui"
#define kEPChooseResult @"kEPChooseResult"
#define kEPResultCacheSucceed @"kEPResultCacheSucceed"
#define kEPSureNextGame @"kEPSureNextGame"
#define kEPComfirmChangeXueci @"kEPComfirmChangeXueci"
#define kEPChangeXueciSucceed @"kEPChangeXueciSucceed"
#define kEPEntryWashNumber @"kEPEntryWashNumber"
#define kEPBenjin @"kEPBenjin"
#define kEPDashui @"kEPDashui"
#define kEPPeifuChip @"kEPPeifuChip"
#define kEPNoChip @"kEPNoChip"
#define kEPSuperDouble @"kEPSuperDouble"
#define kEPDouble @"kEPDouble"
#define kEPPingTimes @"kEPPingTimes"

#define kEPPingTimes @"kEPPingTimes"
#define kEPNiuniu @"kEPNiuniu"
#define kEPFiveCow @"kEPFiveCow"
#define kEPBomb @"kEPBomb"
#define kEPSmallCow @"kEPSmallCow"
#define kEPNoCow @"kEPNoCow"
#define kEPAddChip @"kEPAddChip"
#define kEPDragon @"kEPDragon"
#define kEPTiger @"kEPTiger"
#define kEPTigerHe @"kEPTigerHe"
#define kEPAllKill @"kEPAllKill"
#define kEPHalfKill @"kEPHalfKill"
#define kEPBindChipConfirm @"kEPBindChipConfirm"
#define kEPBindChipSucceed @"kEPBindChipSucceed"
#define kEPClearWashNumberConfirm @"kEPClearWashNumberConfirm"
#define kEPclearSucceed @"kEPclearSucceed"
#define kEPRealpay @"kEPRealpay"
#define kEPShazhu @"kEPShazhu"
#define kEPZhuangshu @"kEPZhuangshu"
#define kEPXianshu @"kEPXianshu"
#define kEPCurrentReadMoney @"kEPCurrentReadMoney"
#define kEPDrgonWin @"kEPDrgonWin"
#define kEPTigerWin @"kEPTigerWin"
#define kEPLookluzhu @"kEPLookluzhu"
#define kEPRecordTipsFee @"kEPRecordTipsFee"
#define kEPDaily @"kEPDaily"

#endif /* EPStrMacro_h */
